let photoDetails = [
  {
    address: "1_bessie_in_grass.jpg",
    size: "big",
    caption: "Bessie in the grass",
    type: "photo",
  },
  {
    address: "2_bessie_lost_pond2.jpg",
    size: "big",
    caption: "Bessie at Lost Pond",
    type: "photo",
  },
  {
    address: "3_bessie_grandma_zoe.jpg",
    size: "big",
    caption: "Bessie Grandma & Zoe",
    type: "photo",
  },
  {
    address: "4_bessie_katie_grandma.jpg",
    size: "big",
    caption: "Bessie Katie & Grandma",
    type: "photo",
  },
  {
    address: "5_bessie_katie_tree.jpg",
    size: "big",
    caption: "Bessie looking up tree",
    type: "photo",
  },
  {
    address: "6_bessie_under_chair.jpg",
    size: "big",
    caption: "Bessie under chair",
    type: "photo",
  },
  {
    address: "7_bessie_with_shoe2013.jpg",
    size: "big",
    caption: "Bessie with slipper",
    type: "photo",
  },
  {
    address: "8_bessie_with_chancey.jpg",
    size: "big",
    caption: "Bessie & Chancey",
    type: "photo",
  },
  {
    address: "9_bessie_closeup.jpg",
    size: "big",
    caption: "Bessie closeup",
    type: "photo",
  },
  {
    address: "10_bessie_3months_old.jpg",
    size: "big",
    caption: "Bessie at 3 months",
    type: "photo",
  },
  {
    address: "11_bessie_digging_snow.jpg",
    size: "normal",
    caption: "Bessie digging in the snow",
    type: "photo",
  },
  {
    address: "12_bessie_in_the_snow.jpg",
    size: "normal",
    caption: "Bessie in the snow",
    type: "photo",
  },
  {
    address: "13_bessie_syd_hiking.jpg",
    size: "wide1",
    caption: "Bessie Steve Sydney hiking",
    type: "photo",
  },
  {
    address: "14_bessie_at_grandmas.jpg",
    size: "big",
    caption: "Bessie at Grandma's",
    type: "photo",
  },
  {
    address: "15_bessie_in_bed.jpg",
    size: "big",
    caption: "Bessie in bed",
    type: "photo",
  },
  {
    address: "16_bessie_colorado_hat.jpg",
    size: "big",
    caption: "Bessie is a Colorado girl",
    type: "photo",
  },
  {
    address: "17_bessie_fuzzy_hair.jpg",
    size: "big",
    caption: "Bessie fuzzy hair with Steve",
    type: "photo",
  },
  {
    address: "18_bessie_couch_katie.jpg",
    size: "wide2",
    caption: "Bessie with Momma Katie",
    type: "photo",
  },
  {
    address: "19_bessie_flower_water.jpg",
    size: "big",
    caption: "Bessie drinking water",
    type: "photo",
  },
  {
    address: "20_bessie_jumping.jpg",
    size: "big",
    caption: "Bessie jumping skyhigh",
    type: "photo",
  },
  {
    address: "21_bessie_foothills.jpg",
    size: "big",
    caption: "Bessie at foothills park with ball",
    type: "photo",
  },
  {
    address: "22_bessie_hiking_guilford.jpg",
    size: "big",
    caption: "Bessie hiking in Guilford",
    type: "photo",
  },
  {
    address: "23_bessie_sanitas_sky.jpg",
    size: "big",
    caption: "Bessie Steve on Sanitas",
    type: "photo",
  },
  {
    address: "24_bessie_dog_house.jpg",
    size: "big",
    caption: "Bessie helping Steve with dog house",
    type: "photo",
  },
  {
    address: "25_bessie_snow_hike.jpg",
    size: "big",
    caption: "Bessie hiking in snow",
    type: "photo",
  },
  {
    address: "26_bessie_hike_view.jpg",
    size: "big",
    caption: "Bessie taking in the view",
    type: "photo",
  },
  {
    address: "27_bessie_winter_coat.jpg",
    size: "big",
    caption: "Bessie winter hike",
    type: "photo",
  },
  {
    address: "28_bessie_grass_roll.jpg",
    size: "big",
    caption: "Bessie grass rolling",
    type: "photo",
  },
  {
    address: "29_bessie_fake_bird.jpg",
    size: "big",
    caption: "Bessie watching bird",
    type: "photo",
  },
  {
    address: "30_bessie_chancey_chase.jpg",
    size: "big",
    caption: "Bessie with Chancey",
    type: "photo",
  },
  {
    address: "31_bessie_chancey_play.jpg",
    size: "big",
    caption: "Bessie with Chancey",
    type: "photo",
  },
  {
    address: "32_bessie_grass_roll.jpg",
    size: "normal",
    caption: "Bessie rolling",
    type: "photo",
  },
  {
    address: "33_bessie_hunting.jpg",
    size: "big",
    caption: "Bessie hunting",
    type: "photo",
  },
  {
    address: "34_bessie_ball.jpg",
    size: "big",
    caption: "Bessie and the ball",
    type: "photo",
  },
  {
    address: "35_bessie_snarl.jpg",
    size: "big",
    caption: "Bessie snarling at Katie for ball",
    type: "photo",
  },
  {
    address: "36_bessie_belly_rub.jpg",
    size: "normal",
    caption: "Bessie belly rubs",
    type: "photo",
  },
  {
    address: "37_BessieInTheMountians022322.png",
    size: "big",
    caption: "Bessie running in snow & mountains",
    type: "photo",
  },
];